### ISSUE TITLE
uri stat 설정 문의

### ISSUE THREAD

**Issue by NobleTuna** [pinpoint-apm/pinpoint#10175]
안녕하세요. 

pinpoint-hbase2-collector-boot-2.5.2.jar
pinpoint-hbase2-web-boot-2.5.2.jar
으로 uri stat 기능이 작동하지 않아 삽질중에 있습니다.

https://github.com/pinpoint-apm/pinpoint/blob/master/uristat/uristat-common/src/main/pinot/pinot-uriStat-realtime-table.json
의 uri-stat topic 생성을 보면 

`$ bin/kafka-topics.sh --create --topic uri-stat --bootstrap-server ${YOUR_KAFKA_SERVER_ADDRESS}`

로 **uri-stat** 토픽을 생성하라고 가이드 되어있는데

[uristat/uristat-common/src/main/pinot/pinot-uriStat-realtime-table.json](https://github.com/pinpoint-apm/pinpoint/blob/master/uristat/uristat-common/src/main/pinot/pinot-uriStat-realtime-table.json)
의 테이블 구성을보면 tream.kafka.topic.name이 **url-stat** 로 되어있습니다.

`    "streamConfigs": {
      "streamType": "kafka",
      "stream.kafka.consumer.type": "lowlevel",
      "stream.kafka.topic.name": "url-stat",`

토픽명이 다른것이 맞는 설정인지 확인부탁드립니다.

아울러 
-Dkafka.uri.topic=url-stat 
옵션을 주소 collector를 실행시켜도 
url-stat 에 들어오는 것이 없는데, 릴리즈된 pinpoint-hbase2-collector-boot-2.5.2.jar 에 url-stat 기능이 포함되어있는지 확인 부탁드립니다.

**Comment by ga-ram** [comment]
As you pointed out, you should create kafka topic with the name `url-stat` to use mentioned `pinot-uriStat-realtime-table.json` configuration file.
I have updated the document accordingly.
https://github.com/pinpoint-apm/pinpoint-apm.github.io/pull/45

Since we no longer support hbase 1 from 2.6.0 (#10131), hbase2 + uri stat + system metric images will be released in v2.6.0

**Comment by NobleTuna** [comment]
@ga-ram 
Thank you.
Close the issue.
