### ISSUE TITLE
Cleanup on application name tab.

### ISSUE THREAD

**Issue by dv-morais** [pinpoint-apm/pinpoint#10605]
Hello everyone,

Nowadays I have hundreds of unused application names in my pinpoint server and cleaning it up by hand is... unpractical.

Is there a way to automatically clean it? or if it already exists how do I acticate it?

thanks in advance.

**Comment by smilu97** [comment]
No we don't currently have something for cleaning application list, I also think we need it

**Comment by smilu97** [comment]
Hi, I'm adding new batch job which cleans up inactive applications. It will actually remove application name if you set property `job.cleanup.inactive.applications.writer=applicationRemover`, otherwise it just checks inactives and log it.

Other default settings can be found on `batch/.../batch-root.properties` file.

Thank you

**Comment by smilu97** [comment]
Cleaning up inactive agents, and applications seem to be merged together. `cleanupInactiveApplicationsJob` will also remove inactive agents, and existing job `cleanupInactiveAgentsJob` will be deprecated later.
