### ISSUE TITLE
When the server has multiple NICs, the Agent may choose a NIC that does not properly communicate with the Collector.

### ISSUE THREAD

**Issue by thisisgpy** [pinpoint-apm/pinpoint#4893]
When the server has multiple NICs, the Agent may choose a NIC that does not properly communicate with the Collector.

The Agent log shows that the startup is normal, but the Agent information is not visible on the Web. Use `netstat -ntpl | grep 9994` to check the network and find that the network packet is blocked on the Send Queue.

So, how can I solve this problem in the case of multiple network cards?

**Comment by koo-taejin** [comment]
hi ganpengyu

First have you checked the firewall problem with the collector?

Then I have difficulty analyzing problems with current information.
Please post  more detail information.

* If the agent does not connect, I wonder how it is recorded in the agent's log.
* What kind of multiple network interface card does agent have? and which network cards were selected?
* I need other helpful information.

thanks.

**Comment by ganpengyu** [comment]
There is a Docker daemon on the application server and Docker will create its own virtual NIC. Since I have created another Docker network, there are multiple NICs on the application server at this time.

When launching the application, I can see that the agent outputs the following log information.

```
[INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
```

This log indicates that the agent started successfully. However, when you use the command `netstat -ntpl | grep 9994` to view the network status, you will find that the agent has selected a wrong network card to establish a connection with the Collector. However, due to some restrictions of the network card, the data is blocked in the Send Queue and cannot be sent to Collector.

So, it can be said that this is not a problem with the Pinpoint Agent itself, but due to complex network card information. My question is, can the Agent support the selection of the specified NIC to establish a connection with the Collector?

**Comment by ganpengyu** [comment]
> hi ganpengyu
> 
> First have you checked the firewall problem with the collector?
> 
> Then I have difficulty analyzing problems with current information.
> Please post more detail information.
> 
> * If the agent does not connect, I wonder how it is recorded in the agent's log.
> * What kind of multiple network interface card does agent have? and which network cards were selected?
> * I need other helpful information.
> 
> thanks.

There is a Docker daemon on the application server and Docker will create its own virtual NIC. Since I have created another Docker network, there are multiple NICs on the application server at this time.

When launching the application, I can see that the agent outputs the following log information.

[INFO ](com.navercorp.pinpoint.bootstrap.PinpointStarter) pinpoint agent started normally.
This log indicates that the agent started successfully. However, when you use the command netstat -ntpl | grep 9994 to view the network status, you will find that the agent has selected a wrong network card to establish a connection with the Collector. However, due to some restrictions of the network card, the data is blocked in the Send Queue and cannot be sent to Collector.

So, it can be said that this is not a problem with the Pinpoint Agent itself, but due to complex network card information. My question is, can the Agent support the selection of the specified NIC to establish a connection with the Collector?

**Comment by koo-taejin** [comment]
I am not familiar with the docker, so I will have difficulty reproduce it 
I will try to reproduce it, but it can take a lot of time.

I understood your issue and will continue to comment if need you're help in reproducing it.

thanks.
