### ISSUE TITLE
Adding arm64 job in Travis-ci

### ISSUE THREAD

**Issue by odidev** [pinpoint-apm/pinpoint#7304]
**Which module is your feature request related to?**

I am trying to add an arm64 job in Travis-ci.

**Is your feature request related to a problem?**

1. Travis-ci is running on trusty distribution which does not run for arm64 and tested against Openjdk6 and Openjdk7 which is outdated and present only in trusty. 

2. **com.google.protobuf:protoc:3.3.0:exe** and **io.grpc:protoc-gen-grpc-java:1.8.0:exe** is not available for arm64.

**Describe the solution you'd like**

1. The trusty distribution is outdated. Is it possible that we can change the distribution and test the package with Openjdk8 and Opendk9 only?

2. After upgrading the version of **com.google.protobuf:protoc** and **io.grpc:protoc-gen-grpc-java**, the code of grpc-java which is copied in https://github.com/naver/pinpoint/blob/master/grpc/src/main/java/io/grpc/internal/PinpointDnsNameResolverProvider.java file also needs to be updated.

**Comment by emeroad** [comment]
We haven't stopped supporting jdk6 yet, so we can't apply the latest Ubuntu.
When we stop supporting jdk 6 in the future, we will upgrade the ubuntu version.

Since pinpoint is pure java, there seems to be no problem with arm64 support.
Please let me know why you want to add the arm64 job to Travis-ci.
