### ISSUE TITLE
[Question] Alarm Interval or Period Configuration (알람 주기 설정 가능 여부)

### ISSUE THREAD

**Issue by dave-ha** [pinpoint-apm/pinpoint#7335]
안녕하세요.
알람 주기 설정 가능 여부를 문의하고자 글을 남깁니다.

현재 핀포인트 2.0.2를 설치해 잘 사용하고 있습니다. 
알람 기능을 설정 후 사용하려고 하는데 알람 주기 설정에 대한 설명이나 기능을 찾기가 어렵네요.

가이드에 "alarm batch는 기본적으로 3분에 한번씩 동작이 된다. 최근 5분동안의 데이터를 수집해서 alarm 조건을 만족하면 user group에 속한 user 들에게 sms /email을 전송한다."라고 되어 있는데요.
최근 5분 동안의 데이터라는 주기를 원하는 시간으로 변경하는 방법이 있을까요? 
예를들어, 최근 1분동안 Error Count 5번 발생할 경우 알림을 보내기 위해서는 어떻게 설정을 변경해야 가능할까요?

가이드가 있지만 제가 찾기 못하고 있는 것이라면 가이드 링크 부탁 드립니다.
만약 가이드가 없지만 방법이 있다면 방법을 알려주실 수 있을까요?
부탁 드립니다.

감사합니다.

================================================================================

Hello,
I got a quick question about alert interval. 
Is it possible I could change the period from 5 minutes to my own?

I am currently using Pinpoint-2.0.2 and trying to use the alarm function.
By default, it uses the last 5 minutes of data for the alarm. I would like to be notified about the threshold per minute.

If anyone reading this issue knows how to configure it, please help me out.

Thank you.

**Comment by dave-ha** [comment]
또한, 한번 알림이 발생한 후 다음 알림을 받는 주기 설정도 조정을 하기 원합니다.
예를들면, 최초 알림 주기는 5분, 두번째 알림 주기를 1시간으로 설정한 경우을 했다고 가정했다고 하자. 그러면 한번 알림이 발생 후 5분 후에 다시 알림을 받는 것이 아닌 두번째 알림은 1시간 후에도 동일한 알림 수치가 발생한 경우 알림 보내도록 설정하기를 희망합니다. 이 부분도 customizing이 가능한지 알고 싶습니다.

**Comment by RoySRose** [comment]
Please translate the title and the comments in English to share the issue with the community

**Comment by minwoo-jung** [comment]
@dave-ha 
The function is not provided for the content you asked.
However, if you implement the code yourself, it will be possible. 
I haven't tried changing the time, so check the normal operation yourself.
The code related to time is mentioned below.
- DataCollectorFactory class, applicationContext-batch-schedule.xml

In order to manage the time, it seems that not only the alarm job itself but also the batch trigger itself should implement code.
