### ISSUE TITLE
Running Pinpoint-Docker on Raspberry Pi

### ISSUE THREAD

**Issue by igo3r** [pinpoint-apm/pinpoint#7479]
I am trying to setup the Pinpoint APM on a Raspberry Pi 3 Model B+ using the pinpoint-docker image. However, as soon as I start by entering "docker-compose pull", I receive the following error:

pi@pinpoint:~ $ cd pinpoint-docker/
pi@pinpoint:~/pinpoint-docker $ sudo docker-compose pull
Pulling pinpoint-mysql      ... done
Pulling zoo1                ... pulling from library/zookeeper
Pulling pinpoint-hbase      ... done
Pulling pinpoint-collector  ... done
Pulling pinpoint-agent      ... done
Pulling pinpoint-quickstart ... done
Pulling pinpoint-web        ... done
Pulling zoo2                ... pulling from library/zookeeper
Pulling zoo3                ... pulling from library/zookeeper
Pulling jobmanager          ... done
Pulling taskmanager         ... done

ERROR: for zoo3  no matching manifest for linux/arm/v7 in the manifest list entries

ERROR: for zoo2  no matching manifest for linux/arm/v7 in the manifest list entries

ERROR: for zoo1  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
pi@pinpoint:~/pinpoint-docker $

My question would be, whether it Is possible to run Pinpoint APM on a Raspberry Pi?

Thanks in advance for your help.

**Comment by erinyees** [comment]
In my opinion, Pinpoint-Docker image is not support for ARM operating system.
ARM operating system can cause a error because most of server are x86 or x64 operating system.

I searched your error(` for zoo3 no matching manifest for linux/arm/v7 in the manifest list entries`) on the Google and I could find similar case with yours.

Ref #1 : ![Link](https://support.circleci.com/hc/en-us/articles/360000347167-No-matching-manifest-for-linux-amd64-in-the-manifest-list-entries)
Ref #2 : ![Link](https://stackoverflow.com/questions/59231697/error-service-mysql-failed-to-build-no-matching-manifest-for-linux-arm-v7-in)

I think if you want to run the pinpoint by using docker then you should make new docker image supporting ARM operating system.

**Comment by erinyees** [comment]
pinpoint founder( @emeroad ) said on #7304

> Since pinpoint is pure java, there seems to be no problem with arm64 support.

so, if you want to run pinpoint on Raspberry Pi 4, how about install pure pinpoint configuration excluding docker?

**Comment by igo3r** [comment]
@erinyees thank you for your comments and your help. I will try to get everything running using the "pure configuration" as suggested
