### ISSUE TITLE
class AgentInfoSender may exist bug

### ISSUE THREAD

**Issue by xinxin2015** [pinpoint-apm/pinpoint#7570]
#### Screenshots
![image](https://user-images.githubusercontent.com/11623622/105474231-0830b300-5cd9-11eb-9aae-26388e081cf7.png)
if max retry exceed,listener cannot perform schedule next action,I think it may be a bug

**Comment by koo-taejin** [comment]
Hi @xinxin2015 

I am going to check what you said. 
After that, I will reply it.

thanks :)

**Comment by koo-taejin** [comment]
@xinxin2015 
I have checked this issue.
I know what you mean.
But, it is impossible to exceed the retryCount value of AgentInfoSender due to the code below.
https://github.com/pinpoint-apm/pinpoint/blob/master/profiler/src/main/java/com/navercorp/pinpoint/profiler/AgentInfoSender.java#L116

There seems to be no problem for this reason.
However, the code will be reinforced.
Thank you.
