### ISSUE TITLE
pinpoint web login page or function

### ISSUE THREAD

**Issue by nhkimm** [pinpoint-apm/pinpoint#8185]
I am using pinpoint web using the jar below.
pinpoint-web-boot-2.3.0.jar

The following are related to Naver pinpoint. There is a web ui login screen, but I can't find it.
https://miro.medium.com/max/700/0*dUaJnQ5yfb-7_9yi

thank you.

**Comment by koo-taejin** [comment]
Hi  @nhkimm 

The Image that you posted is supported from NCLOUD service. 
Unfortunately, You could not use that function because Pinpoint does not have it. 


But Pinpoint supports similliar function(very simple auth).
Please refer this link(https://github.com/pinpoint-apm/pinpoint/issues/7205)


Thanks :)

**Comment by nhkimm** [comment]
thank you.
