### ISSUE TITLE
v2.4.0 update to v2.4.1, application no data 

### ISSUE THREAD

**Issue by dxl727754275** [pinpoint-apm/pinpoint#9102]
os: centos 7.9
docker version: 20.10.10
command:
  docker-compose down
  update env to 2.4.1
  docker-compose up

After docker restarts, the application list is empty and the application has no data. You need to restart the application to collect data, but there are many micro services. How to avoid this problem

**Comment by ga-ram** [comment]
Would you provide more details (e.g., error logs from containers)?
Please check if pinpoint agent has been attached to your application successfully and see if pinpoint collector container is properly connected to hbase.
When I was testing, I had to restart collector container after a few seconds because it was trying to connect to the hbase container when it has no tables available.

**Comment by dxl727754275** [comment]
> Would you provide more details (e.g., error logs from containers)? Please check if pinpoint agent has been attached to your application successfully and see if pinpoint collector container is properly connected to hbase. When I was testing, I had to restart collector container after a few seconds because it was trying to connect to the hbase container when it has no tables available.

I used to use 2.4.0, and the data can be read. After the release of 2.4.1, I upgraded pinpoint to 2.4.1. I found that there was no data after startup, and the log was normal. After I restart the microservice, I can receive the data

**Comment by ga-ram** [comment]
I briefly tested and the problem occurs because there's no saved metadata when you `docker-compose down` as it also shutdowns mysql and hbase as well. Newly collected data are still being collected, just that you could not access them through web easily because application name list saved in hbase are all gone. When you restart your application, it sends its metadata again to collector and then saves it to hbase, so now it is listed on the web. 
Pinpoint assumes those databases are persistent but currently our docker project is there to give you a quick start to experience our project so it may be not suitable for production. I recommend you to set up your own database servers (hbase and mysql). It is also widely recommended to use dockerized databases only for development environment as well.

**Comment by dxl727754275** [comment]
> I briefly tested and the problem occurs because there's no saved metadata when you `docker-compose down` as it also shutdowns mysql and hbase as well. Newly collected data are still being collected, just that you could not access them through web easily because application name list saved in hbase are all gone. When you restart your application, it sends its metadata again to collector and then saves it to hbase, so now it is listed on the web. Pinpoint assumes those databases are persistent but currently our docker project is there to give you a quick start to experience our project so it may be not suitable for production. I recommend you to set up your own database servers (hbase and mysql). It is also widely recommended to use dockerized databases only for development environment as well.

I see. Thank you for your help
