### ISSUE TITLE
About Active Request Error

### ISSUE THREAD

**Issue by king1975** [pinpoint-apm/pinpoint#9311]
Dear All

PinPoint Real Time's View -> Active Request Screen shows "Not Found".

My PinPoint Environment :
Web : 2.4.0
Collector : 2.3.3 (HBase : 1.2.6)
Agent : 2.3.3

When clicking the magnifying glass of Not Found server : 
Error Message 

Http failure response for http://xx.xx.xx.xx:8080/agent/activeThreadLightDump.pinpoint?applicationName=download&ageitId=download1: 500 OK

There is nothing in the agent log.

The strange thing is that if you install PINPOINT WEB on another server, Active Request comes out properly from that server. 
(All environments are the same.)

What should I check? tell me your opinions.

Best Regards.
Thank you.

**Comment by ascendant512** [comment]
Your majesty, 

I learned that this error can occur when the collector process fails to connect to the web process.  One possible cause of this is that the web process is not listening for connections because there is a port conflict (e.g., by two copies of the web process running on the same server at the same time).

It can be verified by checking the connections with ss or netstat, and fixed by configuring the web process to listen on a reachable address and port.
